add janga pvt sensor config
facebook/fboss pull request #302
Opened 2024-12-03 02:30 UTC by zhongedward

# Description

This PR is for tahan pvt sensor config.

# Motivation

1.According to the factory they have added smb card '3 5 20' about productionstate, productversion,productsubversion.
come card '4 1 1' about productionstate, productversion,productsubversion.

![image.png](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/14691/attachments/image.png) 

2.So i have added the following configs.
![image (2).png](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/14691/attachments/image%20%282%29.png) 

# Test Plan

1.The correctness of the format has been verified on this website https://jsonlint.com/ 
2.Used jq cmd to pretty the format.
3.Test log as follows:

![image (3).png](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/14691/attachments/image%20%283%29.png) 

[tahan_main_platform_add_pvt_config_test_log_11_29.txt](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/14691/attachments/tahan_main_platform_add_pvt_config_test_log_11_29.txt) [tahan_main_sensor_add_pvt_config_test_log_11_29.txt](https://dev.azure.com/celestica-hps/89689cf2-cfd3-42fd-afd4-dd867f890ff0/_apis/git/repositories/4c32c16c-7172-448c-b01f-4d18aa18cd31/pullRequests/14691/attachments/tahan_main_sensor_add_pvt_config_test_log_11_29.txt)

2024-12-18 01:18 UTC, mikechoifb requested changes
@zhongedward , this PR breaks Meta's build. Here is the error message we use : 

E1209 22:55:14.066961 3917863 ConfigValidator.cpp:140] PmUnitSensors SlotPath /SMB_FRU_SLOT@0 doesn't match with SlotPath / of /run/devmap/sensors/SMB_U68_TMP422

Slot math seems to mismatch. Can you review the PR again?

2024-12-18 05:13 UTC, zhongedward commented
Hi Mike , thank you for your reply, i have updated the SMB_U68_TMP422 to /SMB_FRU_SLOT@0, and passed the test, please help review again, thanks.

![image](https://github.com/user-attachments/assets/d00c22b6-0baf-4d98-b401-b40511e9c76f)

2024-12-18 05:18 UTC, zhongedward commented
> Hi Mike , thank you for your reply, i have updated the SMB_U68_TMP422 to /SMB_FRU_SLOT@0, and passed the test, please help review again, thanks.
> 
> ![image](https://private-user-images.githubusercontent.com/127284731/396767516-d00c22b6-0baf-4d98-b401-b40511e9c76f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0OTkzNjYsIm5iZiI6MTczNDQ5OTA2NiwicGF0aCI6Ii8xMjcyODQ3MzEvMzk2NzY3NTE2LWQwMGMyMmI2LTBiYWYtNGQ5OC1iNDAxLWI0MDUxMWU5Yzc2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQwNTE3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzk4YjkxNDVmN2IyZjNjMzY0OWM3ZjI5OGIyYjgwMmJmN2RiMTlmMzZkMmU3YzkyOGYyMWE3ZGQxNDUyNTMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.teahszkLEVWWu7jNXbC28O2Sq2oH9a5HDb8O7mLGKX0)

@mikechoifb

2024-12-23 06:35 UTC, zhongedward commented
For clangFormat Lint testing pass, i close this PR turn to the other PR :
https://github.com/facebook/fboss/pull/313

2024-12-23 06:36 UTC, closed without merging